name: CI Pipeline for AKS Store

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all Docker images
        run: |
          docker build -t order-service:${IMAGE_VERSION} ./src/order-service
          docker build -t makeline-service:${IMAGE_VERSION} ./src/makeline-service
          docker build -t product-service:${IMAGE_VERSION} ./src/product-service
          docker build -t store-front:${IMAGE_VERSION} ./src/store-front
          docker build -t store-admin:${IMAGE_VERSION} ./src/store-admin
          docker build -t virtual-customer:${IMAGE_VERSION} ./src/virtual-customer
          docker build -t virtual-worker:${IMAGE_VERSION} ./src/virtual-worker
